// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using studentFreelance.Models;

#nullable disable

namespace studentFreelance.Migrations
{
    [DbContext(typeof(FreelancerDBcontext))]
    [Migration("20220927172215_bidmodel")]
    partial class bidmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("studentFreelance.Models.Bidmodel", b =>
                {
                    b.Property<Guid>("bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FRemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("deadline")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("prID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("bid");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("studentFreelance.Models.freelancer", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("balance")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("college")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("phno")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("email");

                    b.ToTable("freelancer");
                });

            modelBuilder.Entity("studentFreelance.Models.Project", b =>
                {
                    b.Property<Guid>("prID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("deadline")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("prID");

                    b.ToTable("project");
                });

            modelBuilder.Entity("studentFreelance.Models.testModels", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfSubmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("point")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("test");
                });
#pragma warning restore 612, 618
        }
    }
}
