// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using studentFreelance.Models;

#nullable disable

namespace studentFreelance.Migrations.GigDbcontextMigrations
{
    [DbContext(typeof(GigDbcontext))]
    partial class GigDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("studentFreelance.Models.Gig", b =>
                {
                    b.Property<int>("gidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gidId"), 1L, 1);

                    b.Property<string>("amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("gidId");

                    b.ToTable("gig");
                });
#pragma warning restore 612, 618
        }
    }
}
